version: "3.3"
services:
    web:
        image: tubes-1:latest
        ports:
            - 8001:80
        hostname: web
        env_file:
            - .env
        volumes:
            - ./src:/var/www/html

    database:
        image: mysql:latest
        ports:
            - 3316:3306
        hostname: database
        env_file:
            - .env
        volumes:
            - ./mysql:/var/lib/mysql
            - ./init:/docker-entrypoint-initdb.d

networks:
    web-database:
        driver: bridge
